### ISSUE TITLE
build css for pull requests

### ISSUE THREAD

**Issue by maxbachmann** [ottojo/pullRequestHost#3]
since the css is not in the git repo anymore, the go script has to build the css itself.

**Comment by ottojo** [comment]
Maybe this could wait until ToolboxBodensee/toolbox-webseite#220 has been resolved. (Best case would be to push to staging server from travis and deprecate this script)

**Comment by maxbachmann** [comment]
how would you push them with travis?

**Comment by maxbachmann** [comment]
Can you execute "make sass" before executing "lektor build". 
Right now the css is taken from the toolbox website as fallback, so css changes can´t be seen in the pull requests
**Not Used anymore**
